CREATE TABLE Cnabs (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Type INT NOT NULL,
    Date DATE NOT NULL,
    Value DECIMAL(18,2) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    Card VARCHAR(12) NOT NULL,
    Time TIME NOT NULL,
    StoreOwner VARCHAR(14) NOT NULL,
    StoreName VARCHAR(19) NOT NULL
);